OpinionReader/urls.py
from django.urls import path
from .views import IndexView, DetailView

app_name = "OpinionReader"

# these urls come from the tutorial, they're not used anymore.
urlpatterns = [
    #path("main", views.index, name="index"),
    path("", IndexView.as_view(), name="index"),
    # ex: /OpinionViewer/5/
    path("<int:pk>/", DetailView.as_view(), name="detail"),
]

PublicOpinion/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    # 将根目录重定向到名为'my_view'的视图
    path('', lambda _: redirect(reverse_lazy('OpinionReader:index')), name='root_redirect'),
    path("OpinionReader/", include("OpinionReader.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

OpinionReader/models.py
from django.db import models


class Combineddata(models.Model):
    id = models.CharField(db_column='Id', primary_key=True, max_length=100)  # Field name made lowercase.
    author_name = models.CharField(db_column='Author_Name', max_length=100)  # Field name made lowercase.
    author_id = models.CharField(db_column='Author_Id', max_length=100, blank=True, null=True)  # Field name made lowercase.
    author_type = models.CharField(db_column='Author_Type', max_length=50, blank=True, null=True)  # Field name made lowercase.
    content = models.TextField(db_column='Content', blank=True, null=True)  # Field name made lowercase.
    domain = models.CharField(db_column='Domain', max_length=100, blank=True, null=True)  # Field name made lowercase.
    rank = models.FloatField(db_column='Rank', blank=True, null=True)  # Field name made lowercase.
    title = models.CharField(db_column='Title', max_length=200, blank=True, null=True)  # Field name made lowercase.
    read_count = models.IntegerField(db_column='ReadCount', blank=True, null=True)  # Field name made lowercase.
    like_count = models.IntegerField(db_column='LikeCount', blank=True, null=True)  # Field name made lowercase.
    url = models.CharField(db_column='Url', max_length=500, blank=True, null=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date')  # Field name made lowercase.
    comment_count = models.IntegerField(db_column='CommentCount', blank=True, null=True)  # Field name made lowercase.
    forward_count = models.IntegerField(db_column='ForwardCount', blank=True, null=True)  # Field name made lowercase.
    text = models.CharField(db_column='Text', max_length=2000, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CombinedData'


class Keywords(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    key_name = models.CharField(unique=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'Keywords'


class KeywordsAssociation(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    keyword = models.ForeignKey('Keywords', models.DO_NOTHING)
    data = models.ForeignKey('Combineddata', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'keywords_association'
        unique_together = (('data', 'keyword'),)

OpinionReader/views.py
from django.shortcuts import render
from django.views import generic
from django.db.models import Prefetch
from .models import Combineddata, KeywordsAssociation
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = "OpinionReader/index.html"
    context_object_name = "latest_opinion_list"

    def get_queryset(self):
        """Return the last five published questions."""
        # return Combineddata.objects.order_by("-date")[:250]
        # 使用Prefetch预加载关联的Keywords，通过KeywordsAssociation中间表
        prefetch_keywords = Prefetch(
            'keywordsassociation_set',  # 这里使用你的关联表名的小写形式
            queryset=KeywordsAssociation.objects.select_related('keyword'),  # 预先加载Keyword
            to_attr='keywords'  # 将关联的Keyword对象列表存储在'keywords'属性上
        )

        return (
            Combineddata.objects
            .order_by("-date")[:250]
            .prefetch_related(prefetch_keywords)
        )


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Combineddata
    template_name = "OpinionReader/detail.html"

OpinionReader/templates/OpinionReader/detail.html
{% if combineddata.title %}
    <h1>{{ combineddata.title|safe }}</h1>
{% else %}
    <h1>微博</h1>
{% endif %}
{% load filters %}
<ul>

    <li>平台 -- {{ combineddata.domain|get_domain_name }} </li>
    <li>作者 -- {{ combineddata.author_name|safe }} / {{ combineddata.author_id }}</li>
    <li>日期 -- {{ combineddata.date }} </li>
    <li>
        {% if combineddata.domain == 'weibo.com' %}
            {{ combineddata.text|safe }}
        {% else %}
            {{ combineddata.content|safe }}
        {% endif %}
    </li>

</ul>

OpinionReader/templates/OpinionReader/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'OpinionReader/style.css' %}">
{% load filters %}
{% if latest_opinion_list %}
    <table>
        <tr>
            <th scope="col">标题</th>
            <th>标签</th>
            <th>平台</th>
            <th>作者</th>
            <th>日期</th>
            <th>原链接</th>
        </tr>
        {% for opinion in latest_opinion_list %}
            <tr>
                <td>
                    <a href="{% url 'OpinionReader:detail' opinion.id %}">
                        {% if opinion.domain != 'weibo.com' %}
                            {{ opinion.title|safe }}
                        {% else %}
                            {{ opinion.text|safe|slice:"0:30" }}...
                        {% endif %}
                    </a>
                </td>
                <td>
                    {{ opinion.keywords|list_to_string }}
                </td>
                <td>
                    {{ opinion.domain|get_domain_name }}
                </td>
                <td>
                    {{ opinion.author_name|safe }}
                </td>
                <td>
                    {{ opinion.date }}
                </td>
                <td>
                    <a href="{{ opinion.url }}">外网链接</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No opinion is available.</p>
{% endif %}